[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
my_solana_project = "J8rgBzgXESSwUvSHejTr1P6s9e7wWv5Vph1wZquGcbYe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
